### ISSUE TITLE
make fresh fails - unable to open database file: out of memory (14)

### ISSUE THREAD

**Issue by ivishalgandhi** [mr-karan/gullak#1]
Make fresh fails with unable to open database file: out of memory (14)

 File: config.toml
   1   │ [app]
   2   │ debug = true
   3   │ currency = "USD"
   4   │ db_path = "~/data/expenses.db"
   5   │
   6   │ # [openai]
   7   │ # token = "redacted"
   8   │ # timeout = "10s"
   9   │
  10   │ # [telegram]
  11   │ # token = ""
  12   │
  13   │ [openai]
  14   │ base_url = "https://api.groq.com/openai/v1"
  15   │ model = "llama3-70b-8192"
  16   │ token = "xxxxxxx"

~/Sync/foss/gullak on 🌱  main [✓] via 🐋 orbstackvia 🐹 v1.22.4 ⭕️2 took 3s ➜  make fresh
cd ui && yarn install && yarn build
yarn install v1.22.22
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.08s.
yarn run v1.22.22
$ vite build
API URL: http://localhost:3333
vite v5.2.11 building for production...
✓ 3201 modules transformed.
dist/index.html                                                                 1.30 kB │ gzip:  0.64 kB
dist/assets/index-RMWOkjCp.css                                                 28.13 kB │ gzip:  6.00 kB
dist/assets/index-BK07fXIb.js                                                   1.43 kB │ gzip:  0.67 kB
dist/assets/Dashboard-CN0qUjm1.js                                               3.75 kB │ gzip:  1.73 kB
dist/assets/Base-C6g97cQu.js                                                    4.93 kB │ gzip:  1.89 kB
dist/assets/TransactionTable.vue_vue_type_script_setup_true_lang-B1zdHw7a.js   58.31 kB │ gzip: 19.37 kB
dist/assets/Transactions-B02F6LDx.js                                          232.90 kB │ gzip: 72.45 kB
dist/assets/index-CtcriUyN.js                                                 256.49 kB │ gzip: 85.21 kB
✓ built in 3.94s
✨  Done in 4.47s.
CGO_ENABLED=0 go build -o bin/gullak.bin -ldflags="-X 'main.buildString=v0.2.1 (Commit: 2024-06-15 13:06:22 +0530 (2aa84c5), Build: 2024-06-15 10:50:24 -0500)'" .
./bin/gullak.bin
time=2024-06-15T10:50:30.836-05:00 level=INFO msg="Successfully initialized OpenAI client" model=llama3-70b-8192
time=2024-06-15T10:50:30.837-05:00 level=ERROR msg="Error initializing database" error="error creating tables: unable to open database file: out of memory (14)"
make: *** [run] Error 1

**Comment by mr-karan** [comment]
Try giving an absolute path instead of `~` in `db_path`. 

https://stackoverflow.com/a/45039502

**Comment by ivishalgandhi** [comment]
thanks it worked.

**Comment by ivishalgandhi** [comment]
Loved the app @mr-karan. So simple and awesome utility for expense tracking.

**Comment by mr-karan** [comment]
thank you!
